### ISSUE TITLE
Steps for Investigating If Weather Data is the 'Same' 

### ISSUE THREAD

**Issue by rectheworld** [DataKind-DC/audubon-cbc#22]
# Goal: Create a checklist of tasks  and investigation to determine if the weather data reported by CBC volunteers is accurate.

 Pst in the comment below the data investigations you would like to see done or machine learning you want to do.

**Comment by rectheworld** [comment]
For Temperature 
- [ ] Outlier Check 
- who is way off, how is way off 

Basic Stats and Investigations 
- [ ] Take Absolute value of temp difference 
- [ ] Plot over time to look at possible temperature difference
- [ ] Mean Difference 

Are there circles that are more accurate than others? 

Bonus: 
Source check 
- Take the weather data for the following day/ current day, check to see if weather data was taken from the newspaper 

Wind 
- How Should we measure? 

Snow Level 
- [ ] Take Absolute value of temp difference 
- [ ] Existence vs non existence 

Precipitation (Any)
- [ ] Existence vs non existence 

Rain 
- [ ] Existence vs non existence 

Snow 
- [ ] Existances vs non exisitance

**Comment by jd1497** [comment]
Not sure if it's possible for us to look at other research papers out there that's doing similar things (with other biological animals) and see if we could infuse some of their methods into ours? I found some great sources that we can look over with for the following:

- Type of distribution we could use for model building in ecology: Poisson-gamma/ Poisson-lognormal for generalized linear mixed model (Elston 2001 paper on grouse ticks details control on biases for that)

- Temperature that are missing: we can approach it in the following ways:

        1. KNN/K-means/Neural network to determine the temperature (highly recommended, but will look more into that. I'm going to share research papers regarding the same topic)
        2. Leave the missing data as it is and see if they affect the result that we get (maybe we will reach a different conclusion/result if we leave the missing data be)

- Modeling: we do know that time may play a factor (hence we can't escape time series analysis), but do you want us to see whether it was weather and other factors or solely weather that are important in determining bird population? I think that once the data is cleaned, I'm going to do a PCA and pairs to see how the predictive variables are related to each other before modeling, but the data has to be cleaned first.

In the meantime, I hope there's a space for us to post research materials so that we can look over and see how we determine how to go about counting birds!

**Comment by feraguilari** [comment]
To impute missing data we can test imputers from sklearn :
https://scikit-learn.org/stable/modules/impute.html

In regards to modeling, I do believe we could attempt to do a linear regression with 2 features: Distiance to nearest NOAA station and the volunteer temperature reading.

**Comment by dcpatton** [comment]
When trying to determine if the temperature was taken from the paper, it is probably better to compare the TMIN values. Most likely the low temperatures occur overnight and that would likely not be when the CBC volunteers were outside. So there should be more differences in the low temperature values.

**Comment by rectheworld** [comment]
Labeling as Hold because this investigation is taken over by more recent tickets
